[project]
name = "ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docxtpl>=0.20.2",
    "ipykernel>=7.3.0",
    "openpyxl>=3.1.5",
    "paddleocr>=3.7.0",
    "paddlepaddle-gpu==3.3.1",
    "rapidfuzz>=3.14.6",
    "translate>=3.8.1",
]

[project.scripts]
ocr = "ocr:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
paddlepaddle-gpu = { index = "paddlepaddle-gpu" }

[[tool.uv.index]]
name = "paddlepaddle-gpu"
url = "https://www.paddlepaddle.org.cn/packages/stable/cu130/"
explicit = true
